apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-time-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delivery-time-pod
  template:
    metadata:
      labels:
        app: delivery-time-pod
    spec:
      containers:
      - name: delivery-time
        image: myapp:v2
        imagePullPolicy: Never
        env:
        - name: DAGSHUB_USER_TOKEN
          valueFrom:
            secretKeyRef:
              name: dagshub-secret
              key: DAGSHUB_USER_TOKEN
        resources:
          limits:
            memory: "1000Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000


---


apiVersion: v1
kind: Service
metadata:
  name: delivery-time-service
spec:
  selector:
    app: delivery-time-pod
  ports:
  - port: 1234
    targetPort: 8000

